services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Opsone\Varnish\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Opsone\Varnish\Middleware\FrontendSendHeader:
  #   public: true
